server:
  servlet:
    context-path: /api
  port: 8082

spring:
  config:
    import:
      - jpa-mysql.yaml
      - cache.yaml
      - auth.yaml
      - common.yaml

springdoc:
  swagger-ui:
    path: /docs