services:
  redis:
    container_name: spring_labs_redis
    image: redis:latest
    ports:
      - '6380:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 60
    networks:
      - spring_labs

  mysql:
    container_name: spring_labs_mysql
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: spring_labs
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
      - ./infra/mysql/config:/etc/mysql/conf.d
      - ./infra/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 60
    networks:
      - spring_labs

  maxwell:
    container_name: spring_labs_maxwell
    image: zendesk/maxwell
    command: bin/maxwell --config /etc/maxwell/config.properties
    volumes:
      - ./infra/maxwell/config:/etc/maxwell
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - spring_labs

  mongo:
    container_name: spring_labs_mongo
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - ./infra/mongo/data:/data/db
    networks:
      - spring_labs

networks:
  spring_labs:
    name: spring_labs
    driver: bridge