services:
  redis:
    container_name: spring_labs_redis
    image: redis:latest
    ports:
      - '6380:6379'
    networks:
      - spring_labs

  mysql:
    container_name: spring_labs_mysql
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: spring_labs
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - spring_labs

  mongo:
    container_name: spring_labs_mongo
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - ./infra/mongo/data:/data/db
    networks:
      - spring_labs

networks:
  spring_labs:
    driver: bridge