services:
  redis:
    container_name: spring_labs_redis
    image: redis:alpine
    ports:
      - '6380:6379'
    networks:
      - spring_labs

  mysql:
    container_name: spring_labs_mysql
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: spring_labs
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - spring_labs

networks:
  spring_labs:
    driver: bridge